language: go

sudo: enabled
go:
  - 1.9.4
script:
  - go get
  - make
  - sudo apt-get install systemd
  - sudo cp -f /home/travis/gopath/src/github.com/subutai-io/gorjun/libgorjun/gorjun.service /etc/systemd/system/gorjun.service
  - sudo systemctl daemon-reload
  - sudo systemctl start gorjun.service
  - sudo systemctl status gorjun.service
  - sudo apt install -y rng-tools
  - sudo rngd -r /dev/urandom
  - gpg --gen-key --batch /home/travis/gopath/src/github.com/subutai-io/gorjun/libgorjun/gpg.txt
  - sudo chmod +x /home/travis/gopath/src/github.com/subutai-io/gorjun/libgorjun/register.sh
  - cd /home/travis/gopath/src/github.com/emli/subutai-io/libgorjun/; ./register.sh
  - cd /home/travis/gopath/src/github.com/emli/subutai-io/libgorjun; go get github.com/stretchr/testify/assert;
  - go test -v